### PR TITLE
add basic tests

### PR DESCRIPTION
**Pull request by andreineculau**
in order not to be surprised by upcoming nodejs upgrades like in tobiipro/aws-util-firecloud@0e4f9b0

### CODE REVIEW

**Review by IanSavchenko — COMMENTED** [review]
Regarding linter comments: 
1. In the places where you are disabling `jest/prefer-strict-equal` couldn't you use `toMatch` and `toMatchObject`?
2. Had this question before: why do we have the rule `jest/no-test-callback`? What's wrong with that? I read the rule description, which says that people forget to call `done` in scenarios when test fails. But if that happens test will fail anyway with timeout. Otherwise, I see no harm using `done` when you are testing callback-based APIs and don't want to convert to promises (like you have here)

**Comment by andreineculau** [comment]
1. good that you ask, because i was going to ask you if we should turn the rule off. i didn't know about toMatchObject but reading the docs https://jestjs.io/docs/en/expect.html#tomatchobjectobject it's not equivalent. because toEqual will fail if you have more props than what you expect, or so i think. i think we should have it off in the preset, at least based on the experience these days, since you cannot use toBe for non-primitives most of the times

2. i took it as "we prefer async-await pattern vs callback" on top of what the rule description says. with async taking over cb, i think it makes sense to keep it. wdys?

**Comment by IanSavchenko** [comment]
1. I also didn't know about `toEqual` gotcha with extra keys not considered a difference.  I thought that it was your intention to use this and have matching behavior instead of strict equality and you didn't know about `toMatchObject`. This rule makes some sense, so I would probably keep it. But I don't understand why you had to disable it in these cases? Because there were keys with `undefined` values in resulting objects?

2. Ok, let's keep it.

**Comment by andreineculau** [comment]
> I also didn't know about toEqual gotcha with extra keys not considered a difference.

just for clarity:

* `toEqual`: exact deep structure
* `toMatchObject`: subset deep structure

It's `toMatchObject` that will not fail on extra keys.

---

the rest,... I'm \<insert not so nice word\>... I didn't know about `toStrictEqual`. I guess I didn't read the rule description, because I thought it's telling me to use `toBe` thus my previous comment:

> since you cannot use toBe for non-primitives most of the times

**Comment by andreineculau** [comment]
Done. THANKS!

**Review by IanSavchenko — APPROVED** [review]

**Pull request merged**
